#pragma comment(lib, "ws2_32.lib")
#pragma comment(lib, "winmm.lib")
#pragma comment(lib, "FlyCapture2.lib")

#ifdef _DEBUG
#pragma comment(lib, "opencv_calib3d242d.lib")
#pragma comment(lib, "opencv_contrib242d.lib")
#pragma comment(lib, "opencv_core242d.lib")
#pragma comment(lib, "opencv_features2d242d.lib")
//#pragma comment(lib, "opencv_ffmpeg242.lib")
#pragma comment(lib, "opencv_flann242d.lib")
#pragma comment(lib, "opencv_haartraining_engine.lib")
#pragma comment(lib, "opencv_highgui242d.lib")
#pragma comment(lib, "opencv_imgproc242d.lib")
#pragma comment(lib, "opencv_legacy242d.lib")
#pragma comment(lib, "opencv_ml242d.lib")
#pragma comment(lib, "opencv_objdetect242d.lib")
#pragma comment(lib, "opencv_ts242d.lib")
#pragma comment(lib, "opencv_video242d.lib")
#pragma comment(lib, "opencv_gpu242d.lib")
#pragma comment(lib, "zlibd.lib")
#pragma comment(lib, "libtiffd.lib")
#pragma comment(lib, "libjpegd.lib")
#pragma comment(lib, "libpngd.lib")
#pragma comment(lib, "libjasperd.lib")
//#pragma comment(lib, "FlyCapture2GUI_Cd.lib")
#else
#pragma comment(lib, "opencv_calib3d242.lib")
#pragma comment(lib, "opencv_contrib242.lib")
#pragma comment(lib, "opencv_core242.lib")
#pragma comment(lib, "opencv_features2d242.lib")
//#pragma comment(lib, "opencv_ffmpeg242.lib")
#pragma comment(lib, "opencv_flann242.lib")
#pragma comment(lib, "opencv_haartraining_engine.lib")
#pragma comment(lib, "opencv_highgui242.lib")
#pragma comment(lib, "opencv_imgproc242.lib")
#pragma comment(lib, "opencv_legacy242.lib")
#pragma comment(lib, "opencv_ml242.lib")
#pragma comment(lib, "opencv_objdetect242.lib")
#pragma comment(lib, "opencv_ts242.lib")
#pragma comment(lib, "opencv_video242.lib")
#pragma comment(lib, "opencv_gpu242.lib")
#pragma comment(lib, "zlib.lib")
#pragma comment(lib, "libtiff.lib")
#pragma comment(lib, "libjpeg.lib")
#pragma comment(lib, "libpng.lib")
#pragma comment(lib, "libjasper.lib")
//#pragma comment(lib, "FlyCapture2GUI.lib")
#endif

